name       : haskell-conduit-extra
version    : 1.3.5
release    : 3
source     :
    - https://hackage.haskell.org/package/conduit-extra-1.3.5/conduit-extra-1.3.5.tar.gz : 8a648dee203c01e647fa386bfe7a5b293ce552f8b5cab9c0dd5cb71c7cd012d9
license    : MIT
component  : programming.haskell
summary    : The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
description: |
    The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
builddeps  :
    - haskell-attoparsec-devel
    - haskell-cabal-install
    - haskell-conduit-devel
    - haskell-mono-traversable-devel
    - haskell-split-devel
    - haskell-streaming-commons-devel
    - haskell-typed-process-devel
rundeps    :
    - devel:
        - haskell-attoparsec-devel
        - haskell-conduit-devel
        - haskell-mono-traversable-devel
        - haskell-split-devel
        - haskell-streaming-commons-devel
        - haskell-typed-process-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
