name       : haskell-conduit-extra
version    : 1.1.15
release    : 1
source     :
    - http://hackage.haskell.org/package/conduit-extra-1.1.15/conduit-extra-1.1.15.tar.gz : 7bef29eb0db59c236519b0c5cac82183ed7741a535a57e0772aac1158e90bb8d
license    : MIT
component  : programming.haskell
summary    : The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
description: |
    The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
builddeps  :
    - haskell-attoparsec
    - haskell-cabal-install
    - haskell-conduit
    - haskell-primitive
    - haskell-streaming-commons
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
