name       : haskell-conduit-extra
version    : 1.3.0
release    : 2
source     :
    - http://hackage.haskell.org/package/conduit-extra-1.3.0/conduit-extra-1.3.0.tar.gz : 2c41c925fc53d9ba2e640c7cdca72c492b28c0d45f1a82e94baef8dfa65922ae
license    : MIT
component  : programming.haskell
summary    : The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
description: |
    The purpose of this package is to collect commonly used utility functions wrapping other library dependencies, without depending on heavier-weight dependencies.
builddeps  :
    - haskell-attoparsec
    - haskell-cabal-install
    - haskell-conduit
    - haskell-primitive
    - haskell-streaming-commons
    - haskell-typed-process
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
